#!/bin/bash -ex

# Switch to the app root dir
cd /var/www/html

# Install composer
if [ ! -e composer.phar ]; then
  curl -sS https://getcomposer.org/installer | php
fi

# Run composer
if [ -e composer.json ]; then
  php composer.phar install
fi
